#[project]
#name = "buildcost-gh-backend"
#version = "0.1.0"
#requires-python = ">=3.13"
#dependencies = [
#    "alembic>=1.19.1",
#    "anthropic>=1.3.0",
#    "apscheduler>=3.11.3",
#    "argon2-cffi>=25.1.0",
#    "fastapi[standard]>=0.141.1",
#    "httpx>=0.28.1",
#    "jinja2>=3.1.6",
#    "pandas>=3.0.5",
#    "passlib[bcrypt]>=1.7.4",
#    "pgvector>=0.5.0",
#    "psycopg2-binary>=2.9.12",
#    "pydantic>=2.13.5",
#    "python-dotenv>=1.2.3",
#    "python-jose[cryptography]>=3.5.0",
#    "reportlab>=5.0.1",
#    "sqlalchemy>=2.0.52",
#    "uliweb-alembic>=0.6.9",
#    "unicorn>=2.1.4",
#    "uvicorn>=0.52.4",
#]


[project]
name = "buildcost-gh-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "anthropic>=1.3.0",
    "apscheduler>=3.11.3",
    "argon2-cffi>=25.1.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pandas>=3.0.5",
    "passlib[bcrypt]>=1.7.4",
    "pgvector>=0.5.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "reportlab>=5.0.1",
    "sqlalchemy>=2.0.52",
    "uliweb-alembic>=0.6.9",
    "unicorn>=2.1.4",
    "uvicorn>=0.52.4",
]
