"""fixed date issues since they were appearing as null

Revision ID: 10479fe0dfb3
Revises: 99101e248f64
Create Date: 2026-09-03 20:49:27.226974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10479fe0dfb3'
down_revision: Union[str, Sequence[str], None] = '99101e248f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('estimates', 'created_at')
    op.alter_column('labor_rates', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('land_prices', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('materials', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('permits', 'date',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permits', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('materials', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('land_prices', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('labor_rates', 'date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.add_column('estimates', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('estimates', 'date')
    # ### end Alembic commands ###
