"""new upadtes

Revision ID: 252b08d53bbf
Revises: 545ce0b6a643
Create Date: 2026-09-04 10:49:33.459303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252b08d53bbf'
down_revision: Union[str, Sequence[str], None] = '545ce0b6a643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
