"""made some updates in my schemas and models

Revision ID: 2a8a4c1a0123
Revises: f789581f890e
Create Date: 2026-09-04 07:49:00.581745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a8a4c1a0123'
down_revision: Union[str, Sequence[str], None] = 'f789581f890e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('estimates', 'user_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('estimates', 'itemized',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('estimates', 'total',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('estimates', 'confidence',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('estimates', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feedback', 'estimate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feedback', 'actual_cost',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('feedback', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('labor_rates', sa.Column('district', sa.String(), nullable=False))
    op.alter_column('labor_rates', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('labor_rates', 'trade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('labor_rates', 'rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('labor_rates', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('labor_rates', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_labor_rates_district'), 'labor_rates', ['district'], unique=False)
    op.add_column('land_prices', sa.Column('region', sa.String(), nullable=False))
    op.alter_column('land_prices', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('land_prices', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('land_prices', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('land_prices', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_land_prices_district'), 'land_prices', ['district'], unique=False)
    op.create_index(op.f('ix_land_prices_region'), 'land_prices', ['region'], unique=False)
    op.alter_column('materials', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('materials', 'item',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('materials', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('materials', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('materials', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('materials', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('permits', sa.Column('district', sa.String(), nullable=False))
    op.alter_column('permits', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permits', 'fee_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permits', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('permits', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('permits', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_permits_district'), 'permits', ['district'], unique=False)
    op.alter_column('saved_estimates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('saved_estimates', 'estimate',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('saved_estimates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('saved_estimates', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('saved_estimates', 'estimate',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('saved_estimates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_permits_district'), table_name='permits')
    op.alter_column('permits', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('permits', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('permits', 'amount',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('permits', 'fee_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('permits', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('permits', 'district')
    op.alter_column('materials', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('materials', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('materials', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('materials', 'item',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('materials', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_land_prices_region'), table_name='land_prices')
    op.drop_index(op.f('ix_land_prices_district'), table_name='land_prices')
    op.alter_column('land_prices', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('land_prices', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('land_prices', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('land_prices', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('land_prices', 'region')
    op.drop_index(op.f('ix_labor_rates_district'), table_name='labor_rates')
    op.alter_column('labor_rates', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_rates', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('labor_rates', 'rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('labor_rates', 'trade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('labor_rates', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('labor_rates', 'district')
    op.alter_column('feedback', 'submitted_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feedback', 'actual_cost',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('feedback', 'estimate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('estimates', 'date',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('estimates', 'confidence',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('estimates', 'total',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('estimates', 'itemized',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('estimates', 'user_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
