"""made some updates in my models: district addition to materials

Revision ID: 545ce0b6a643
Revises: 2a8a4c1a0123
Create Date: 2026-09-04 08:38:04.438621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545ce0b6a643'
down_revision: Union[str, Sequence[str], None] = '2a8a4c1a0123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('district', sa.String(), nullable=True))
    op.create_index(op.f('ix_materials_district'), 'materials', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_district'), table_name='materials')
    op.drop_column('materials', 'district')
    # ### end Alembic commands ###
