"""dis

Revision ID: 903d9859fbe7
Revises: 1e79e93de742
Create Date: 2026-09-04 11:31:51.502086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903d9859fbe7'
down_revision: Union[str, Sequence[str], None] = '1e79e93de742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_district'), table_name='materials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_materials_district'), 'materials', ['district'], unique=False)
    # ### end Alembic commands ###
