"""changed date to time in my models

Revision ID: 9a4d0a00ea05
Revises: d9e1f3a4b5c6
Create Date: 2026-09-12 12:14:10.110334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a4d0a00ea05'
down_revision: Union[str, Sequence[str], None] = 'd9e1f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_estimates_user_id'), table_name='estimates')
    op.drop_column('estimates', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_estimates_user_id'), 'estimates', ['user_id'], unique=False)
    op.drop_column('estimates', 'time')
    # ### end Alembic commands ###
