"""Making new changes to my DB

Revision ID: ecad0d79aab8
Revises: 9a4d0a00ea05
Create Date: 2026-09-12 12:54:52.596258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecad0d79aab8'
down_revision: Union[str, Sequence[str], None] = '9a4d0a00ea05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
