"""fixed date issues since they were appearing as null again now

Revision ID: f789581f890e
Revises: 1832965cae15
Create Date: 2026-09-03 20:58:12.664634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'f789581f890e'
down_revision: Union[str, Sequence[str], None] = '1832965cae15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None




def upgrade():
    op.alter_column("materials", "date", type_=sa.TIMESTAMP, server_default=sa.func.now())
    op.execute(text("UPDATE materials SET date = NOW() WHERE date IS NULL"))

    op.alter_column("labor_rates", "date", type_=sa.TIMESTAMP, server_default=sa.func.now())
    op.execute(text("UPDATE labor_rates SET date = NOW() WHERE date IS NULL"))

    op.alter_column("land_prices", "date", type_=sa.TIMESTAMP, server_default=sa.func.now())
    op.execute(text("UPDATE land_prices SET date = NOW() WHERE date IS NULL"))

    op.alter_column("permits", "date", type_=sa.TIMESTAMP, server_default=sa.func.now())
    op.execute(text("UPDATE permits SET date = NOW() WHERE date IS NULL"))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
